CREATE DATABASE payroll;
USE payroll;

CREATE TABLE jobdept (
	JOB_CODE CHAR(2) NOT NULL KEY,
	JOB_DESC VARCHAR(20) NOT NULL,
	JOB_DEPT VARCHAR(20) NOT NULL
);

CREATE TABLE salary (
	SALARY_ID CHAR(4) NOT NULL KEY,
    JOB_CODE CHAR(2) NOT NULL,
	FOREIGN KEY (JOB_CODE) REFERENCES jobdept(JOB_CODE),
	SALARY_AMOUNT DECIMAL(9,2) NOT NULL
);

CREATE TABLE employee (
	EMP_ID CHAR(4) NOT NULL KEY,
	EMP_LNAME VARCHAR(20) NOT NULL,
	EMP_FNAME VARCHAR(20) NOT NULL,
	EMP_GENDER VARCHAR(1),
	EMP_ADD VARCHAR(20) NOT NULL,
    JOB_CODE CHAR(2),
	CONSTRAINT JOB_CODE FOREIGN KEY (JOB_CODE) REFERENCES jobdept(JOB_CODE),
	EMP_CONTACT_NUMBER CHAR(13) NOT NULL,
    SALARY_ID CHAR(4),
    CONSTRAINT SALARY_ID FOREIGN KEY (SALARY_ID) REFERENCES salary(SALARY_ID),
    EMP_HOURS_WORKED INT NOT NULL
);


CREATE TABLE bonuses (
	BONUS_ID CHAR(4) NOT NULL KEY,
    EMP_ID CHAR(4) NOT NULL,
    FOREIGN KEY (EMP_ID) REFERENCES employee(EMP_ID),
    BONUS_REASON VARCHAR(20),
    BONUS_AMOUNT DECIMAL(9,2)
);

CREATE TABLE deductions (
	DEDUCTION_ID CHAR(4) NOT NULL KEY,
    EMP_ID CHAR(4) NOT NULL,
    FOREIGN KEY (EMP_ID) REFERENCES employee(EMP_ID),
    DEDUCTION_REASON VARCHAR(20),
    DEDUCTION_AMOUNT DECIMAL(9,2)
);

CREATE TABLE leaves (
	LEAVE_ID CHAR(4) NOT NULL KEY,
    EMP_ID CHAR(4) NOT NULL,
    FOREIGN KEY (EMP_ID) REFERENCES employee(EMP_ID),
    DATE_OF_LEAVE DATE
);

CREATE TABLE payroll (
    PAYROLL_ID CHAR(4) NOT NULL KEY,
    EMP_ID CHAR(4) NOT NULL,
    JOB_CODE CHAR(2) NOT NULL,
    SALARY_ID CHAR(4) NOT NULL,
    LEAVE_ID CHAR(4),
    DEDUCTION_ID CHAR(4),
    BONUS_ID CHAR(4),
    FOREIGN KEY (EMP_ID)
        REFERENCES employee (EMP_ID),
    FOREIGN KEY (JOB_CODE)
        REFERENCES jobdept (JOB_CODE),
    FOREIGN KEY (SALARY_ID)
        REFERENCES salary (SALARY_ID),
    FOREIGN KEY (LEAVE_ID)
        REFERENCES leaves (LEAVE_ID),
    FOREIGN KEY (DEDUCTION_ID)
        REFERENCES deductions (DEDUCTION_ID),
    FOREIGN KEY (BONUS_ID)
        REFERENCES bonuses (BONUS_ID),
    TOTAL_AMOUNT DECIMAL(9 , 2 ) NOT NULL
);